import { BrandConfig, CaseStyle } from '../types/customizer';

export const BRANDS_DATA: BrandConfig[] = [
  {
    id: 'apple',
    name: 'Apple',
    devices: [
      // iPhone 17
      {
        id: 'iphone-17-pro-max',
        brand: 'apple',
        name: 'iPhone 17 Pro Max',
        generation: 'iPhone 17',
        mockupImagePath: '/MockupsV2/Iphone17/Iphone17promax.png',
        dimensions: {
          width: 3.07,
          height: 6.43,
          depth: 0.34,
          cornerRadius: 0.44,
          realWidthMm: 78.0,
          realHeightMm: 163.4,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.68, 1.95, 0.17],
          width: 1.3,
          height: 1.4,
          depth: 0.11,
          radius: 0.3,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 4.5,
          moduleY: 8.5,
          moduleWidth: 68.0,
          moduleHeight: 42.0,
          moduleRadius: 10.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-17-pro',
        brand: 'apple',
        name: 'iPhone 17 Pro',
        generation: 'iPhone 17',
        mockupImagePath: '/MockupsV2/Iphone17/iphone17pro.png',
        dimensions: {
          width: 2.83,
          height: 5.9,
          depth: 0.34,
          cornerRadius: 0.43,
          realWidthMm: 71.9,
          realHeightMm: 150.0,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.65, 1.78, 0.17],
          width: 1.25,
          height: 1.35,
          depth: 0.11,
          radius: 0.29,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 4.5,
          moduleY: 8.5,
          moduleWidth: 62.0,
          moduleHeight: 39.0,
          moduleRadius: 10.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-17-air',
        brand: 'apple',
        name: 'iPhone 17 Air',
        generation: 'iPhone 17',
        mockupImagePath: '/MockupsV2/Iphone17/Iphone17air.png',
        dimensions: {
          width: 2.94,
          height: 6.15,
          depth: 0.22,
          cornerRadius: 0.42,
          realWidthMm: 74.7,
          realHeightMm: 156.2,
        },
        camera: {
          type: 'single-lens',
          position: [-0.8, 1.9, 0.14],
          width: 0.7,
          height: 1.1,
          depth: 0.08,
          radius: 0.28,
          lensCount: 1,
          hasFlash: true,
          hasLidar: false,
          moduleX: 9.0,
          moduleY: 10.0,
          moduleWidth: 33.0,
          moduleHeight: 27.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-17',
        brand: 'apple',
        name: 'iPhone 17',
        generation: 'iPhone 17',
        mockupImagePath: '/MockupsV2/Iphone17/Iphone17.png',
        dimensions: {
          width: 2.81,
          height: 5.89,
          depth: 0.31,
          cornerRadius: 0.42,
          realWidthMm: 71.5,
          realHeightMm: 149.6,
        },
        camera: {
          type: 'vertical-pill-modern',
          position: [-0.78, 1.82, 0.16],
          width: 0.65,
          height: 1.32,
          depth: 0.09,
          radius: 0.32,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 10.0,
          moduleWidth: 31.0,
          moduleHeight: 38.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone 16
      {
        id: 'iphone-16-pro-max',
        brand: 'apple',
        name: 'iPhone 16 Pro Max',
        generation: 'iPhone 16',
        mockupImagePath: '/MockupsV2/Iphone16/Iphone16promax.png',
        dimensions: {
          width: 3.02,
          height: 6.42,
          depth: 0.32,
          cornerRadius: 0.44,
          realWidthMm: 77.6,
          realHeightMm: 163.0,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.68, 1.95, 0.17],
          width: 1.28,
          height: 1.38,
          depth: 0.11,
          radius: 0.3,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 5.0,
          moduleY: 9.0,
          moduleWidth: 42.0,
          moduleHeight: 42.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-16-pro',
        brand: 'apple',
        name: 'iPhone 16 Pro',
        generation: 'iPhone 16',
        mockupImagePath: '/MockupsV2/Iphone16/Iphone16pro.png',
        dimensions: {
          width: 2.85,
          height: 5.89,
          depth: 0.32,
          cornerRadius: 0.43,
          realWidthMm: 71.5,
          realHeightMm: 149.6,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.65, 1.78, 0.17],
          width: 1.22,
          height: 1.32,
          depth: 0.11,
          radius: 0.29,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 4.5,
          moduleY: 9.0,
          moduleWidth: 40.0,
          moduleHeight: 40.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-16-plus',
        brand: 'apple',
        name: 'iPhone 16 Plus',
        generation: 'iPhone 16',
        mockupImagePath: '/MockupsV2/Iphone16/Iphone16plus.png',
        dimensions: {
          width: 3.06,
          height: 6.34,
          depth: 0.31,
          cornerRadius: 0.44,
          realWidthMm: 77.8,
          realHeightMm: 160.9,
        },
        camera: {
          type: 'vertical-pill-modern',
          position: [-0.85, 2.05, 0.16],
          width: 0.68,
          height: 1.38,
          depth: 0.09,
          radius: 0.34,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 9.0,
          moduleY: 11.0,
          moduleWidth: 34.0,
          moduleHeight: 40.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-16',
        brand: 'apple',
        name: 'iPhone 16',
        generation: 'iPhone 16',
        mockupImagePath: '/MockupsV2/Iphone16/Iphone16.png',
        dimensions: {
          width: 2.82,
          height: 5.81,
          depth: 0.31,
          cornerRadius: 0.42,
          realWidthMm: 71.6,
          realHeightMm: 147.6,
        },
        camera: {
          type: 'vertical-pill-modern',
          position: [-0.78, 1.82, 0.16],
          width: 0.65,
          height: 1.32,
          depth: 0.09,
          radius: 0.32,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 9.0,
          moduleY: 11.0,
          moduleWidth: 31.0,
          moduleHeight: 38.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone 15
      {
        id: 'iphone-15-pro-max',
        brand: 'apple',
        name: 'iPhone 15 Pro Max',
        generation: 'iPhone 15',
        mockupImagePath: '/MockupsV2/Iphone15/Iphone15promax.png',
        dimensions: {
          width: 3.02,
          height: 6.29,
          depth: 0.32,
          cornerRadius: 0.42,
          realWidthMm: 76.7,
          realHeightMm: 159.9,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.68, 1.92, 0.17],
          width: 1.24,
          height: 1.34,
          depth: 0.1,
          radius: 0.28,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 5.0,
          moduleY: 9.0,
          moduleWidth: 41.0,
          moduleHeight: 41.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-15-pro',
        brand: 'apple',
        name: 'iPhone 15 Pro',
        generation: 'iPhone 15',
        mockupImagePath: '/MockupsV2/Iphone15/Iphone15pro.png',
        dimensions: {
          width: 2.78,
          height: 5.77,
          depth: 0.32,
          cornerRadius: 0.42,
          realWidthMm: 70.6,
          realHeightMm: 146.6,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.65, 1.74, 0.17],
          width: 1.18,
          height: 1.28,
          depth: 0.1,
          radius: 0.28,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 5.0,
          moduleY: 9.0,
          moduleWidth: 39.0,
          moduleHeight: 39.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-15-plus',
        brand: 'apple',
        name: 'iPhone 15 Plus',
        generation: 'iPhone 15',
        mockupImagePath: '/MockupsV2/Iphone15/Iphone15plus.png',
        dimensions: {
          width: 3.06,
          height: 6.33,
          depth: 0.31,
          cornerRadius: 0.4,
          realWidthMm: 77.8,
          realHeightMm: 160.9,
        },
        camera: {
          type: 'diagonal-dual',
          position: [-0.82, 2.05, 0.16],
          width: 1.08,
          height: 1.08,
          depth: 0.09,
          radius: 0.26,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.0,
          moduleWidth: 34.0,
          moduleHeight: 34.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-15',
        brand: 'apple',
        name: 'iPhone 15',
        generation: 'iPhone 15',
        mockupImagePath: '/MockupsV2/Iphone15/Iphone15.png',
        dimensions: {
          width: 2.82,
          height: 5.81,
          depth: 0.31,
          cornerRadius: 0.4,
          realWidthMm: 71.6,
          realHeightMm: 147.6,
        },
        camera: {
          type: 'diagonal-dual',
          position: [-0.74, 1.82, 0.16],
          width: 1.05,
          height: 1.05,
          depth: 0.09,
          radius: 0.26,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.0,
          moduleWidth: 32.0,
          moduleHeight: 32.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone 14
      {
        id: 'iphone-14-pro-max',
        brand: 'apple',
        name: 'iPhone 14 Pro Max',
        generation: 'iPhone 14',
        mockupImagePath: '/MockupsV2/Iphone14/Iphone14promax.png',
        dimensions: {
          width: 3.06,
          height: 6.33,
          depth: 0.31,
          cornerRadius: 0.4,
          realWidthMm: 77.6,
          realHeightMm: 160.7,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.7, 1.95, 0.17],
          width: 1.25,
          height: 1.35,
          depth: 0.1,
          radius: 0.28,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 6.5,
          moduleY: 10.0,
          moduleWidth: 41.0,
          moduleHeight: 41.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-14-pro',
        brand: 'apple',
        name: 'iPhone 14 Pro',
        generation: 'iPhone 14',
        mockupImagePath: '/MockupsV2/Iphone14/Iphone14pro.png',
        dimensions: {
          width: 2.81,
          height: 5.81,
          depth: 0.31,
          cornerRadius: 0.38,
          realWidthMm: 71.5,
          realHeightMm: 147.5,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.66, 1.76, 0.17],
          width: 1.18,
          height: 1.28,
          depth: 0.1,
          radius: 0.28,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 6.0,
          moduleY: 10.0,
          moduleWidth: 39.0,
          moduleHeight: 39.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-14-plus',
        brand: 'apple',
        name: 'iPhone 14 Plus',
        generation: 'iPhone 14',
        mockupImagePath: '/MockupsV2/Iphone14/Iphone14plus.png',
        dimensions: {
          width: 3.07,
          height: 6.33,
          depth: 0.31,
          cornerRadius: 0.38,
          realWidthMm: 78.1,
          realHeightMm: 160.8,
        },
        camera: {
          type: 'diagonal-dual',
          position: [-0.82, 2.05, 0.16],
          width: 1.05,
          height: 1.05,
          depth: 0.08,
          radius: 0.25,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.0,
          moduleWidth: 34.0,
          moduleHeight: 34.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-14',
        brand: 'apple',
        name: 'iPhone 14',
        generation: 'iPhone 14',
        mockupImagePath: '/MockupsV2/Iphone14/Iphone14.png',
        dimensions: {
          width: 2.81,
          height: 5.78,
          depth: 0.31,
          cornerRadius: 0.38,
          realWidthMm: 71.5,
          realHeightMm: 146.7,
        },
        camera: {
          type: 'diagonal-dual',
          position: [-0.74, 1.82, 0.16],
          width: 1.02,
          height: 1.02,
          depth: 0.08,
          radius: 0.25,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.0,
          moduleWidth: 32.0,
          moduleHeight: 32.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone 13
      {
        id: 'iphone-13-pro-max',
        brand: 'apple',
        name: 'iPhone 13 Pro Max',
        generation: 'iPhone 13',
        mockupImagePath: '/MockupsV2/Iphone13/Iphone13promax.png',
        dimensions: {
          width: 3.07,
          height: 6.33,
          depth: 0.3,
          cornerRadius: 0.38,
          realWidthMm: 78.1,
          realHeightMm: 160.8,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.72, 1.98, 0.17],
          width: 1.2,
          height: 1.3,
          depth: 0.1,
          radius: 0.27,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 7.0,
          moduleY: 10.5,
          moduleWidth: 39.0,
          moduleHeight: 39.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-13-pro',
        brand: 'apple',
        name: 'iPhone 13 Pro',
        generation: 'iPhone 13',
        mockupImagePath: '/MockupsV2/Iphone13/Iphone13pro.png',
        dimensions: {
          width: 2.81,
          height: 5.78,
          depth: 0.3,
          cornerRadius: 0.36,
          realWidthMm: 71.5,
          realHeightMm: 146.7,
        },
        camera: {
          type: 'triple-pro-large',
          position: [-0.66, 1.76, 0.17],
          width: 1.15,
          height: 1.25,
          depth: 0.1,
          radius: 0.27,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 6.5,
          moduleY: 10.5,
          moduleWidth: 37.0,
          moduleHeight: 37.0,
          moduleRadius: 7.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-13',
        brand: 'apple',
        name: 'iPhone 13',
        generation: 'iPhone 13',
        mockupImagePath: '/MockupsV2/Iphone13/Iphone13.png',
        dimensions: {
          width: 2.81,
          height: 5.78,
          depth: 0.3,
          cornerRadius: 0.36,
          realWidthMm: 71.5,
          realHeightMm: 146.7,
        },
        camera: {
          type: 'diagonal-dual',
          position: [-0.74, 1.82, 0.15],
          width: 1.0,
          height: 1.0,
          depth: 0.08,
          radius: 0.25,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.0,
          moduleWidth: 32.0,
          moduleHeight: 32.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-13-mini',
        brand: 'apple',
        name: 'iPhone 13 mini',
        generation: 'iPhone 13',
        mockupImagePath: '/MockupsV2/Iphone13/Iphone13mini.png',
        dimensions: {
          width: 2.53,
          height: 5.18,
          depth: 0.3,
          cornerRadius: 0.34,
          realWidthMm: 64.2,
          realHeightMm: 131.5,
        },
        camera: {
          type: 'diagonal-dual',
          position: [-0.62, 1.62, 0.15],
          width: 0.94,
          height: 0.94,
          depth: 0.08,
          radius: 0.24,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 7.5,
          moduleY: 11.0,
          moduleWidth: 29.5,
          moduleHeight: 29.5,
          moduleRadius: 6.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone 12
      {
        id: 'iphone-12-pro-max',
        brand: 'apple',
        name: 'iPhone 12 Pro Max',
        generation: 'iPhone 12',
        mockupImagePath: '/MockupsV2/Iphone12/Iphone12promax.png',
        dimensions: {
          width: 3.07,
          height: 6.33,
          depth: 0.29,
          cornerRadius: 0.36,
          realWidthMm: 78.1,
          realHeightMm: 160.8,
        },
        camera: {
          type: 'triple-pro-classic',
          position: [-0.76, 2.05, 0.15],
          width: 1.12,
          height: 1.2,
          depth: 0.08,
          radius: 0.26,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 8.0,
          moduleY: 11.5,
          moduleWidth: 35.0,
          moduleHeight: 35.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-12-pro',
        brand: 'apple',
        name: 'iPhone 12 Pro',
        generation: 'iPhone 12',
        mockupImagePath: '/MockupsV2/Iphone12/Iphone12pro.png',
        dimensions: {
          width: 2.81,
          height: 5.78,
          depth: 0.29,
          cornerRadius: 0.35,
          realWidthMm: 71.5,
          realHeightMm: 146.7,
        },
        camera: {
          type: 'triple-pro-classic',
          position: [-0.7, 1.82, 0.15],
          width: 1.05,
          height: 1.15,
          depth: 0.08,
          radius: 0.25,
          lensCount: 3,
          hasFlash: true,
          hasLidar: true,
          moduleX: 7.5,
          moduleY: 11.5,
          moduleWidth: 32.5,
          moduleHeight: 32.5,
          moduleRadius: 6.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-12',
        brand: 'apple',
        name: 'iPhone 12',
        generation: 'iPhone 12',
        mockupImagePath: '/MockupsV2/Iphone12/Iphone12.png',
        dimensions: {
          width: 2.81,
          height: 5.78,
          depth: 0.29,
          cornerRadius: 0.35,
          realWidthMm: 71.5,
          realHeightMm: 146.7,
        },
        camera: {
          type: 'vertical-dual-square',
          position: [-0.76, 1.88, 0.15],
          width: 0.95,
          height: 1.02,
          depth: 0.07,
          radius: 0.24,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 12.0,
          moduleWidth: 31.0,
          moduleHeight: 31.0,
          moduleRadius: 6.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-12-mini',
        brand: 'apple',
        name: 'iPhone 12 mini',
        generation: 'iPhone 12',
        mockupImagePath: '/MockupsV2/Iphone12/Iphone12mini.png',
        dimensions: {
          width: 2.53,
          height: 5.18,
          depth: 0.29,
          cornerRadius: 0.33,
          realWidthMm: 64.2,
          realHeightMm: 131.5,
        },
        camera: {
          type: 'vertical-dual-square',
          position: [-0.64, 1.68, 0.15],
          width: 0.9,
          height: 0.96,
          depth: 0.07,
          radius: 0.23,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 7.5,
          moduleY: 11.5,
          moduleWidth: 28.5,
          moduleHeight: 28.5,
          moduleRadius: 6.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone 11
      {
        id: 'iphone-11-pro-max',
        brand: 'apple',
        name: 'iPhone 11 Pro Max',
        generation: 'iPhone 11',
        mockupImagePath: '/MockupsV2/Iphone11/Iphone11promax.png',
        dimensions: {
          width: 3.06,
          height: 6.22,
          depth: 0.32,
          cornerRadius: 0.4,
          realWidthMm: 77.8,
          realHeightMm: 158.0,
        },
        camera: {
          type: 'triple-pro-classic',
          position: [-0.76, 2.02, 0.15],
          width: 1.08,
          height: 1.16,
          depth: 0.07,
          radius: 0.25,
          lensCount: 3,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 12.0,
          moduleWidth: 37.0,
          moduleHeight: 37.0,
          moduleRadius: 7.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-11-pro',
        brand: 'apple',
        name: 'iPhone 11 Pro',
        generation: 'iPhone 11',
        mockupImagePath: '/MockupsV2/Iphone11/Iphone11pro.png',
        dimensions: {
          width: 2.81,
          height: 5.67,
          depth: 0.32,
          cornerRadius: 0.38,
          realWidthMm: 71.4,
          realHeightMm: 144.0,
        },
        camera: {
          type: 'triple-pro-classic',
          position: [-0.7, 1.8, 0.15],
          width: 1.02,
          height: 1.1,
          depth: 0.07,
          radius: 0.24,
          lensCount: 3,
          hasFlash: true,
          hasLidar: false,
          moduleX: 7.5,
          moduleY: 11.5,
          moduleWidth: 36.0,
          moduleHeight: 36.0,
          moduleRadius: 7.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-11',
        brand: 'apple',
        name: 'iPhone 11',
        generation: 'iPhone 11',
        mockupImagePath: '/MockupsV2/Iphone11/Iphone11.png',
        dimensions: {
          width: 2.98,
          height: 5.94,
          depth: 0.33,
          cornerRadius: 0.42,
          realWidthMm: 75.7,
          realHeightMm: 150.9,
        },
        camera: {
          type: 'vertical-dual-square',
          position: [-0.8, 1.95, 0.15],
          width: 0.95,
          height: 1.08,
          depth: 0.07,
          radius: 0.25,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.8,
          moduleY: 12.0,
          moduleWidth: 34.0,
          moduleHeight: 34.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },

      // iPhone X / XS / XR / SE
      {
        id: 'iphone-xs-max',
        brand: 'apple',
        name: 'iPhone XS Max',
        generation: 'iPhone X / XS',
        dimensions: {
          width: 3.05,
          height: 6.2,
          depth: 0.3,
          cornerRadius: 0.4,
          realWidthMm: 77.4,
          realHeightMm: 157.5,
        },
        camera: {
          type: 'vertical-pill-classic',
          position: [-0.95, 2.15, 0.14],
          width: 0.48,
          height: 1.15,
          depth: 0.06,
          radius: 0.24,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.5,
          moduleY: 12.0,
          moduleWidth: 15.0,
          moduleHeight: 32.0,
          moduleRadius: 7.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-xs',
        brand: 'apple',
        name: 'iPhone XS',
        generation: 'iPhone X / XS',
        dimensions: {
          width: 2.79,
          height: 5.65,
          depth: 0.3,
          cornerRadius: 0.38,
          realWidthMm: 70.9,
          realHeightMm: 143.6,
        },
        camera: {
          type: 'vertical-pill-classic',
          position: [-0.85, 1.9, 0.14],
          width: 0.46,
          height: 1.1,
          depth: 0.06,
          radius: 0.23,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.5,
          moduleWidth: 14.5,
          moduleHeight: 31.0,
          moduleRadius: 7.25,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-x',
        brand: 'apple',
        name: 'iPhone X',
        generation: 'iPhone X / XS',
        dimensions: {
          width: 2.79,
          height: 5.65,
          depth: 0.3,
          cornerRadius: 0.38,
          realWidthMm: 70.9,
          realHeightMm: 143.6,
        },
        camera: {
          type: 'vertical-pill-classic',
          position: [-0.85, 1.9, 0.14],
          width: 0.46,
          height: 1.1,
          depth: 0.06,
          radius: 0.23,
          lensCount: 2,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.5,
          moduleWidth: 14.5,
          moduleHeight: 31.0,
          moduleRadius: 7.25,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-xr',
        brand: 'apple',
        name: 'iPhone XR',
        generation: 'iPhone XR / SE',
        dimensions: {
          width: 2.98,
          height: 5.94,
          depth: 0.33,
          cornerRadius: 0.42,
          realWidthMm: 75.7,
          realHeightMm: 150.9,
        },
        camera: {
          type: 'single-lens',
          position: [-0.88, 2.05, 0.14],
          width: 0.52,
          height: 0.92,
          depth: 0.06,
          radius: 0.26,
          lensCount: 1,
          hasFlash: true,
          hasLidar: false,
          moduleX: 9.0,
          moduleY: 12.0,
          moduleWidth: 14.0,
          moduleHeight: 14.0,
          moduleRadius: 7.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
      {
        id: 'iphone-se-3',
        brand: 'apple',
        name: 'iPhone SE (2da / 3ra Gen)',
        generation: 'iPhone XR / SE',
        dimensions: {
          width: 2.65,
          height: 5.45,
          depth: 0.29,
          cornerRadius: 0.38,
          realWidthMm: 67.3,
          realHeightMm: 138.4,
        },
        camera: {
          type: 'single-lens',
          position: [-0.85, 2.0, 0.14],
          width: 0.45,
          height: 0.85,
          depth: 0.06,
          radius: 0.22,
          lensCount: 1,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 11.0,
          moduleWidth: 13.0,
          moduleHeight: 13.0,
          moduleRadius: 6.5,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#121212',
      },
    ],
  },
  {
    id: 'samsung',
    name: 'Samsung',
    devices: [
      {
        id: 'samsung-s24-ultra',
        brand: 'samsung',
        name: 'Galaxy S24 Ultra',
        generation: 'Galaxy S24',
        dimensions: {
          width: 3.11,
          height: 6.39,
          depth: 0.34,
          cornerRadius: 0.12,
          realWidthMm: 79.0,
          realHeightMm: 162.3,
        },
        camera: {
          type: 'vertical-quad',
          position: [-0.8, 1.85, 0.16],
          width: 0.95,
          height: 2.1,
          depth: 0.1,
          radius: 0.2,
          lensCount: 4,
          hasFlash: true,
          hasLidar: true,
          moduleX: 8.0,
          moduleY: 12.0,
          moduleWidth: 26.0,
          moduleHeight: 65.0,
          moduleRadius: 6.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#1a1a1a',
      },
      {
        id: 'samsung-s24-plus',
        brand: 'samsung',
        name: 'Galaxy S24+',
        generation: 'Galaxy S24',
        dimensions: {
          width: 2.99,
          height: 6.24,
          depth: 0.3,
          cornerRadius: 0.38,
          realWidthMm: 75.9,
          realHeightMm: 158.5,
        },
        camera: {
          type: 'vertical-triple',
          position: [-0.95, 2.05, 0.15],
          width: 0.48,
          height: 1.85,
          depth: 0.08,
          radius: 0.24,
          lensCount: 3,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 12.0,
          moduleWidth: 16.0,
          moduleHeight: 52.0,
          moduleRadius: 8.0,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#1a1a1a',
      },
      {
        id: 'samsung-s24',
        brand: 'samsung',
        name: 'Galaxy S24',
        generation: 'Galaxy S24',
        dimensions: {
          width: 2.78,
          height: 5.79,
          depth: 0.3,
          cornerRadius: 0.36,
          realWidthMm: 70.6,
          realHeightMm: 147.0,
        },
        camera: {
          type: 'vertical-triple',
          position: [-0.88, 1.88, 0.15],
          width: 0.46,
          height: 1.75,
          depth: 0.08,
          radius: 0.23,
          lensCount: 3,
          hasFlash: true,
          hasLidar: false,
          moduleX: 8.0,
          moduleY: 12.0,
          moduleWidth: 15.5,
          moduleHeight: 50.0,
          moduleRadius: 7.75,
        },
        customizableMeshName: 'CaseBackCustomMesh',
        customizationArea: { x: 0, y: 0, width: 1, height: 1 },
        defaultCaseColor: '#1a1a1a',
      },
    ],
  },
];

export const CASE_STYLES_DATA: CaseStyle[] = [
  {
    id: 'matte-black',
    name: 'Negro Mate Premium',
    color: '#121316',
    opacity: 1.0,
    roughness: 0.72,
    metalness: 0.05,
    transmission: 0,
    clearcoat: 0.1,
  },
  {
    id: 'glossy-white',
    name: 'Blanco Puro Brillante',
    color: '#f8fafc',
    opacity: 1.0,
    roughness: 0.15,
    metalness: 0.05,
    transmission: 0,
    clearcoat: 0.85,
  },
  {
    id: 'midnight-blue',
    name: 'Azul Medianoche',
    color: '#0f172a',
    opacity: 1.0,
    roughness: 0.45,
    metalness: 0.15,
    transmission: 0,
    clearcoat: 0.35,
  },
  {
    id: 'transparent',
    name: 'Transparente Antiamarilleo',
    color: '#ffffff',
    opacity: 0.28,
    roughness: 0.08,
    metalness: 0.1,
    transmission: 0.92,
    clearcoat: 1.0,
  },
  {
    id: 'crimson-red',
    name: 'Rojo Carmesí',
    color: '#881337',
    opacity: 1.0,
    roughness: 0.4,
    metalness: 0.2,
    transmission: 0,
    clearcoat: 0.4,
  },
  {
    id: 'emerald-green',
    name: 'Verde Esmeralda',
    color: '#064e3b',
    opacity: 1.0,
    roughness: 0.42,
    metalness: 0.18,
    transmission: 0,
    clearcoat: 0.38,
  },
];

export const CASE_STYLES = CASE_STYLES_DATA;
export const DEFAULT_DEVICE = BRANDS_DATA[0].devices[0];
export const DEFAULT_CASE_STYLE = CASE_STYLES_DATA[0];

